{{- $fullName := .Values.appName -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-blue
  labels:
    release: {{ $fullName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "blue-green.name" . }}
data:
  # When the config map is mounted as a volume, these will be created as files
  {{- (.Files.Glob "environment.properties").AsConfig | nindent 2 }}
